[package]
edition = "2018"
name = "metadata-core"
version = "0.2.1"
authors = ["fluvio.io"]


[dependencies]
log = "0.4.5"
serde = { version ="1.0.82", features = ['derive'] }
serde_json = "1.0.27"
serde_qs = "0.4.1"
hyper = "0.12.25"

