[package]
edition = "2018"
name = "metadata-topic"
version = "0.2.1"
authors = ["fluvio.io"]


[dependencies]
log = "0.4.8"
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.39"
metadata-core = { path = "../metadata-core"}

