[package]
edition = "2018"
name = "flv-k8-topic"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Topic for K8"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[dependencies]
log = "0.4.8"
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.39"
k8-obj-metadata = { version = "0.1.0" }


