apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: partitions.fluvio.infinyon.com
spec:
  group: fluvio.infinyon.com
  version: v1
  names:
    kind: Partition
    plural: partitions
    singular: partition
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Leader
      type: integer
      format: int32
      description: Spu Id
      JSONPath: .spec.leader
    - name: Followers
      type: string
      description: Followers
      JSONPath: .spec.replicas
    - name: Status
      type: string
      description: Partition Status
      JSONPath: .status.resolution
    - name: LSR
      type: integer
      format: int32
      description: Live Replicas
      JSONPath: .status.lsr
    - name: HW
      type: integer
      format: int64
      description: Leader High Watermark
      JSONPath: .status.leader.hw
    - name: EOF
      type: integer
      format: int64
      description: Leader End Offset
      JSONPath: .status.leader.leo
    - name: Follower Offsets
      type: string
      description: Follower Offsets
      JSONPath: .status.replicas
  validation:
    openAPIV3Schema:
      type: object
      required: ["spec"]
      properties:
        spec:
          type: object
          required: ["leader", "replicas"]
          properties:
            leader:
              type: integer
            replicas:
              type: array
              items:
                type: integer
