[package]
name = "metadata"
edition = "2018"
version = "0.2.0-alpha.1"
authors = ["fluvio.io"]

[dependencies]
log = "0.4.6"
kf-protocol = { path = "../kf-protocol"}
k8-metadata = { path = "../k8-metadata"}
types = { path = "../types"}