[workspace]
members = [
    "src/cli",
    "src/client-rs",
    "src/client-node",
    "src/api/internal-api",
    "src/kf-protocol",
    "src/kf-protocol/kf-protocol-dump",
#    "kf-protocol/kf-protocol-build",
    "src/kf-socket",
    "src/kf-service",
    "src/k8-metadata",
    "src/metadata",
    "src/api/sc-api",
    "src/sc-core",
    "src/sc-k8",
    "src/api/spu-api",
    "src/spu-server",
    "src/storage",
    "src/test-helper",
    "src/types",
    "src/utils",
    "src/proxy"
]

[patch.crates-io]
##k8-client = { path = "../k8-api/src/k8-client" }
##k8-metadata-client = { path = "../k8-api/src/k8-metadata-client"}
##k8-obj-core = { path = "../k8-api/src/k8-obj-core"}
##k8-obj-app = { path = "../k8-api/src/k8-obj-app"}
##k8-obj-metadata = { path = "../k8-api/src/k8-obj-metadata"}
#k8-config = { path = "../k8-api/src/k8-config"}
#k8-diff = { path = "../k8-api/src/k8-diff"}
flv-future-aio = { path = "../flv-future/src/future-aio"}
##node-bindgen = { path = "../node-bindgen"}

# profile to make image sizer smaller
# comment out for now
#[profile.release]
#lto = true
#codegen-units = 1
#incremental = false