[package]
name = "kf-protocol-transport"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]


[dependencies]
log = "0.4.6"
bytes = "0.4.12"
futures_codec = "0.3.1"
kf-protocol = { path = "../kf-protocol-core", package = "kf-protocol-core" }


[dev-dependencies]
future-helper = { path = "../../future-helper", features = ["fixture"] }
futures = { version = "0.3.1" }
future-aio = { path = "../../future-aio"}
utils = { path= "../../utils"}