[package]
name = "spu-api"
version = "0.2.0-alpha.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.6"
kf-protocol = { path = "../../kf-protocol"}
kf-socket = {path = "../../kf-socket"}
utils = { path= "../../utils"}
serde = { version ="1.0.82", features = ['derive'] }