[package]
edition = "2018"
name = "metadata-client"
version = "0.2.1"
authors = ["fluvio.io"]



[dependencies]
log = "0.4.8"
futures = { version = "0.3.1"}
pin-utils = "0.1.0-alpha.4"
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.40"
serde_qs = "0.5.0"
async-trait = "0.1.21"
flv-future-core = { version = "0.1.0" }
k8-diff = { path = "../../k8-diff"}
types = { path ="../../types", package = "flv-types"}
metadata-core = { path = "../metadata-core"}

