[package]
name = "spu-api"
version = "0.2.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.8"
utils = { path= "../../utils"}
serde = { version ="1.0.103", features = ['derive'] }
kf-protocol = { path = "../../kf-protocol"}
flv-future-aio = { path = "../../future-aio"}