[package]
name = "internal-api"
version = "0.2.3"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.8"
kf-protocol = { version = "1.1.3" } 
flv-metadata = { path = "../metadata"}
flv-types = { path ="../types" }
