[package]
name = "kf-protocol-transport"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]


[dependencies]
log = "0.4.8"
bytes = "0.5.3"
futures_codec = "0.3.4"
flv-future-aio = { version = "0.1.0" }
kf-protocol = { path = "../kf-protocol-core", package = "kf-protocol-core" }

[dev-dependencies]
flv-future-core = { version = "0.1.0", features = ["fixture"] }
futures = { version = "0.3.1" }
flv-util = { version = "0.1.0"}