[package]
name = "kf-protocol-transport"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]


[dependencies]
log = "0.4.8"
bytes = "0.5.3"
futures_codec = "0.3.4"
flv-future-aio = { path = "../../future-aio"}
kf-protocol = { path = "../kf-protocol-core", package = "kf-protocol-core" }


[dev-dependencies]
flv-future-core = { path = "../../future-helper", features = ["fixture"] }
futures = { version = "0.3.1" }
utils = { path= "../../utils"}