[package]
name = "flv-integration-test"
version = "0.2.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.8"
bytes = "0.5.3"
futures = { version = "0.3.1" }
flv-future-core = { version = "0.1.0" }
kf-protocol = { path = "../kf-protocol"}
kf-socket = {path = "../kf-socket"}
kf-service = { path = "../kf-service"}
internal-api = { path = "../api/internal-api"}
types = { path= "../types"}
utils = { path= "../utils"}
flv-metadata = { path = "../metadata" }
flv-future-aio = { version = "0.1.0" }
