[package]
name = "kf-socket"
version = "0.2.1"
edition = "2018"
authors = ["fluvio.io"]

[[bin]]
name = "file_send"
path = "src/bin/file_send.rs"
doc = false
required-features = ["cli"]



[dependencies]
log = "0.4.8"
bytes = "0.5.3"
futures = { version = "0.3.1" }
pin-utils = "0.1.0-alpha.4"
chashmap = "2.2.0"
futures_codec = "0.3.1"
kf-protocol = { path = "../kf-protocol"}
flv-future-aio = { version = "0.1.0" }
flv-future-core = { version = "0.1.0" }


[dev-dependencies]
flv-util = { version = "0.1.0", features = ["fixture"]}
flv-future-core = { version = "0.1.0", features = ["fixture"] }
