[package]
name = "kf-socket"
version = "1.1.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Provide TCP socket wrapper using kafka protocol"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
categories = ["encoding"]

[[bin]]
name = "file_send"
path = "src/bin/file_send.rs"
doc = false
required-features = ["cli"]



[dependencies]
log = "0.4.8"
bytes = "0.5.3"
futures = { version = "0.3.4" }
pin-utils = "0.1.0-alpha.4"
chashmap = "2.2.0"
tokio-util = { version = "0.3.1", features = ["codec","compat"]} 
async-trait = "0.1.21"
kf-protocol = { version = "1.1.0", path = "../kf-protocol"}
flv-future-aio = { version = "2.0.0", features = ["tls"] }


[dev-dependencies]
flv-util = { version = "0.1.0", features = ["fixture"]}
flv-future-aio = { version = "2.0.0", features = ["fixture"] }
