[package]
name = "kf-protocol-core"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]


[dependencies]
bytes = "0.4.12"
log = "0.4.8"
num-traits = "0.2.6"
num-derive = "0.2.4"
utils = { path= "../../utils"}
serde = { version ="1.0.103", features = ['derive'] }