[package]
name = "flv-metadata"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]

[dependencies]
log = "0.4.8"
kf-protocol = { version = "0.1.0", path = "../kf-protocol"}
k8-flv-metadata = { path = "../k8-metadata"}
types = { version = "0.1.0", path ="../types", package = "flv-types"}