[package]
name = "flv-metadata"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]

[dependencies]
log = "0.4.8"
kf-protocol = { path = "../kf-protocol"}
k8-metadata = { path = "../k8-metadata"}
types = { path = "../types"}