[package]
name = "internal-api"
version = "0.2.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.8"
kf-protocol = { path = "../../kf-protocol"}
flv-metadata = { path = "../../metadata"}
types = { path ="../../types", package = "flv-types"}
