[package]
name = "internal-api"
version = "0.2.0-alpha.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.6"
kf-protocol = { path = "../../kf-protocol"}
metadata = { path = "../../metadata"}
types = { path= "../../types"}
