apiVersion: v1
kind: Service
metadata:
  name: group1
  labels:
    app: spu
    group: group1
spec:
  ports:
  - name: public
    protocol: TCP
    port: 9005
    targetPort: 9005
  - name: private
    protocol: TCP
    port: 9006
    targetPort: 9006
  clusterIP: None
  type: ClusterIP
  selector:
    app: spu
    group: group1