apiVersion: v1
kind: Service
metadata:
  name: spu-1
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: spu-1
  ports:
  - protocol: TCP
    port: 9005
    targetPort: 9005