[package]
name = "flv-types"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2018"
description = "Fluvio common types"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"

[dependencies]
log = "0.4.8"