[package]
name = "utils"
version = "0.2.2"
authors = ["fluvio.io"]
edition = "2018"

[features]
default = []
fixture = []

[dependencies]
regex = "1.3.1"
log = "0.4.8"
rand = "0.7.2"
flv-types = { path ="../types", version = "0.2.0"}
