[package]
name = "flv-client"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
repository = "https://github.com/infinyon/fluvio"
description = "Fluvio rust client"


[dependencies]
log = "0.4.8"
rand = "0.7.2"
dirs = "1.0.2"
toml = "0.5.5"
futures = { version = "0.3.1", features = ['async-await'] }
async-trait = "0.1.22"
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.39"
flv-future-core = { version = "0.1.0" }
flv-future-aio = { version = "0.1.0" }
kf-protocol = { version = "0.1.0", path = "../kf-protocol"}
types = { version = "0.1.0", path ="../types", package = "flv-types"}
kf-socket = { version = "0.1.0", path = "../kf-socket" }
sc-api = { path = "../api/sc-api", version = "0.1.0", package = "flv-api-sc"}
spu-api = { path = "../api/spu-api",version = "0.1.0", package = "flv-api-spu"}
