[package]
edition = "2018"
name = "flv-storage"
version = "0.2.1"
authors = ["fluvio.io"]

[[bin]]
name = "storage-cli"
path = "src/bin/cli.rs"
doc = false
required-features = ["cli"]


[dependencies]
log = "0.4.8"
libc = "0.2.58"
bytes = "0.5.3"
futures = { version = "0.3.1" }
pin-utils = "0.1.0-alpha.4"
async-trait = "0.1.18"
structopt = { version = "0.3.5", optional = true}
serde = { version ="1.0.103", features = ['derive'] }
flv-future-aio = { path = "../future-aio"}
kf-protocol = { path = "../kf-protocol"}
kf-socket = { path = "../kf-socket"}
flv-future-core = { path = "../future-helper" }
utils = { path= "../utils", optional = false }
types = { path= "../types"}


[dev-dependencies]
flv-future-core = { path = "../future-helper", features=["fixture"]}
utils = { path = "../utils", features = ["fixture"]}



[features]
cli = ["structopt"]