[package]
edition = "2018"
name = "kf-service"
version = "2.0.0"
authors = ["fluvio.io"]

[dependencies]
log = "0.4.8"
futures = { version = "0.3.4", features = ["async-await"] }
async-trait = "0.1.21"
pin-utils = "0.1.0-alpha.4"
kf-protocol = { version = "1.1.2", path = "../kf-protocol"}
flv-future-aio = { version = "2.1.0", features = ["tls"] }
kf-socket = { version = "1.1.0", path = "../kf-socket"}
types = { version = "0.1.0", path ="../types", package = "flv-types"}

[dev-dependencies]
flv-future-aio = { version = "2.1.0", features = ["fixture"] }
flv-util = { version = "0.1.0" }