[package]
name = "flv-sc-core"
edition = "2018"
version = "1.0.0"
authors = ["fluvio.io"]

[dependencies]
rand = "0.7.2"
log = "0.4.8"
toml = "0.5.5"
serde = { version ="1.0.103", features = ['derive'] }
futures = { version = "0.3.1" }
chashmap = "2.2.0"
base64 = "0.11.0"
regex = "1.3.1"
async-trait = "0.1.21"
flv-util = { version = "0.1.1"}
flv-future-aio = { version = "2.0.0", features =["tls"] }
k8-metadata-client = { version = "1.0.0"}
types = { path ="../types", package = "flv-types"}
utils = { path = "../utils"}
kf-protocol = { path = "../kf-protocol"}
kf-socket = {path = "../kf-socket"}
kf-service = { path = "../kf-service"}
internal-api = { path = "../api/internal-api"}
k8-flv-metadata = { version = "1.0.0", path = "../k8-metadata"}
flv-metadata = { path = "../metadata"}
sc-api = { version = "1.0.0", path = "../api/sc-api", package = "flv-api-sc"}

[dev-dependencies]
flv-future-aio = { version = "2.0.0", features=["fixture"]}
flv-util = { version = "0.1.1", features=["fixture"]}
