[package]
name = "flv-sc-core"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]

[dependencies]
rand = "0.7.2"
log = "0.4.8"
toml = "0.5.5"
serde = { version ="1.0.103", features = ['derive'] }
futures = { version = "0.3.1" }
chashmap = "2.2.0"
base64 = "0.11.0"
regex = "1.3.1"
async-trait = "0.1.21"
types = { path = "../types"}
utils = { path = "../utils"}
flv-future-core = { path = "../future-helper" }
kf-protocol = { path = "../kf-protocol"}
kf-socket = {path = "../kf-socket"}
kf-service = { path = "../kf-service"}
internal-api = { path = "../api/internal-api"}
k8-metadata = { path = "../k8-metadata"}
flv-metadata = { path = "../metadata"}
sc-api = { path = "../api/sc-api"}

[dev-dependencies]
flv-future-core = { path = "../future-helper", features=["fixture"]}
flv-future-aio = { path = "../future-aio"}
k8-fixtures = { path = "../k8-client/k8-fixtures" }
utils = { path = "../utils", features=["fixture"]}
