[package]
name = "fluvio-client"
version = "0.2.1"
edition = "2018"
authors = ["fluvio.io"]
license = "Apache-2.0"
repository = "https://github.com/infinyon/fluvio"
homepage = "fluvio.io"
description = "Client for Fluvio"
categories = ["stream", "fluvio", "client","stateful"]

[dependencies]
log = "0.4.8"
futures = { version = "0.3.1", features = ['async-await'] }
future-helper = { path = "../future-helper" }
future-aio = { path = "../future-aio"}
kf-protocol = { path = "../kf-protocol"}
kf-socket = { path = "../kf-socket" }
sc-api = { path = "../api/sc-api"}
spu-api = { path = "../api/spu-api"}

