[package]
name = "async-test-derive"
version = "0.2.1"
edition = "2018"
authors = ["fluvio.io"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.24"
quote = "0.6.10"
syn = { version = "0.15.23", features = ["full"] }
log = "0.4.6"
