apiVersion: v1
kind: Pod
metadata:
  name: flv-sc
  labels:
    app: flv-sc
spec:
  containers:
    - name: flv-sc
      image: infinyon/fluvio-sc:0.2.1
      imagePullPolicy: Never
      ports:
        - containerPort: 9003
      env:
        - name: RUST_LOG
          value: sc_server=debug