apiVersion: v1
kind: Service
metadata:
  name: flv-sc-internal
spec:
  selector:
    app: flv-sc
  ports:
  - protocol: TCP
    port: 9004
    targetPort: 9004
---
apiVersion: v1
kind: Service
metadata:
  name: flv-sc-internal
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: flv-sc
  ports:
  - protocol: TCP
    port: 9004
    targetPort: 9004