[package]
name = "sc-api"
version = "0.2.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.8"
kf-protocol = { version = "0.1.0", path = "../../kf-protocol"}
flv-metadata = { path = "../../metadata"}
utils = { path= "../../utils"}
types = { path ="../../types", package = "flv-types"}
serde = { version ="1.0.103", features = ['derive'] }
k8-flv-metadata = { path = "../../k8-metadata"}