[package]
name = "metadata-partition"
version = "0.1.0-alpha.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.6"
serde = { version ="1.0.82", features = ['derive'] }
serde_json = "1.0.27"
metadata-core = { path = "../metadata-core"}