[package]
name = "flv-sc-k8"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]

[[bin]]
name = "sc-k8-server"
path = "src/main.rs"
doc = false

[dependencies]
rand = "0.7.2"
log = "0.4.8"
toml = "0.5.5"
structopt = "0.3.5"
futures = { version = "0.3.1" }
k8-client = { version = "0.2.1"}
types = { path ="../types", package = "flv-types"}
utils = { path = "../utils"}
flv-future-core = { version = "0.1.0" }
flv-util = { version = "0.1.0"}
k8-flv-metadata = { path = "../k8-metadata"}
flv-sc-core = { path = "../sc-core"}
k8-config = { version = "0.1.0" }
flv-metadata = { path = "../metadata"}
